I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 686, in script
    m"Oi."
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 686, in script
    m"Oi."
  File "/Volumes/renpy-7.3.5-sdk/renpy-7.3.5-sdk/renpy/ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Volumes/renpy-7.3.5-sdk/renpy-7.3.5-sdk/renpy/ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Darwin-19.3.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
WGJ20project 1.0
Sun Aug 23 19:18:52 2020
